### ISSUE TITLE
How to preprocess JourneyDB captions

### ISSUE THREAD

**Issue by kgmills** [VinAIResearch/SwiftBrush#1]
Hello,

I like this work a lot. 1-step distillation using only prompts is very good. 

I'm wondering if you can provide a script for deduplicating JourneyDB into the .txt file you use in the code.
I recently got access to JourneyDB and am wondering how you preprocessed/filtered the captions. I can see the training data has over 4M entries, but you deduplicated this down to 2M. How?

Also, all the entries in JourneyDB have a 'prompt' entry, but most also have a ['Task2']['caption'] entry which is more coherent sentence (prompt is like tag words). Which do you use?

When I deduplicate, I get 1.38M entries using the 'prompt' key, and around 1.41M using the 'caption' key, for reference.

Thanks!

**Comment by thuanz123** [comment]
1.38M is correct. We will update the paper.
